# Site settings
title: SugarScape
email: chenye84@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for simulation, evolution and intelligence.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sugarscape.net" # the base hostname & protocol for your site
github_username:  chenye

# Build settings
markdown: kramdown
