url:
baseurl:

# Site settings
title: SugarScape
email: chenye84@gmail.com
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
description: "SugarScape: the place where artificial intelligence emerges."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/chenye
  - title: linkedin
    url: https://www.linkedin.com/pub/ye-chen/56/9b8/606

# Build settings
markdown: kramdown
permalink: pretty
